# Generated by Django 3.2.4 on 2021-06-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
